Repository Ritikraja07/Java-problem-Open-Source, pull requests merged in 2023-10, with the labels that each got.

#2 Stack Using Array
  StackUsingArray.java
Labels: hacktoberfest, hacktoberfest2023

#4 Added stack using queue
  stackUsingQueue$Stack.class
  stackUsingQueue.class
  stackUsingQueue.java
Labels: hacktoberfest, hacktoberfest2023

#6 Add emailmasker
  EmailMasker.java
Labels: hacktoberfest, hacktoberfest2023

#5 Created Boolean_matrix.java
  Boolean_matrix.java
Labels: hacktoberfest, hacktoberfest2023

#7 Create hanoi.java
  hanoi.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#9 Create Palindrome.java
  Palindrome.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#8 Create FindTotalNumberOfNodesInBST
  FindTotalNumberOfNodesInBST
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#12 Revert " linkedlist"
  linkedlist.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#13 binarysearch
  binarysearch.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#14 reverse
  reverse.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#17 Armstrong number Program
  Armstrong.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#16 Java problem added with the solution
  all_subsequences_with_sum_equal_k.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#15 Create Radix_sort.java
  Radix_sort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#18 Create Column_name_for_given_Column_Number.java
  Column_name_for_given_Column_Number.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#20 Create largest_sum_subarray(kadanes_algorithm)
  largest_sum_subarray(kadanes_algorithm)
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#19 Added Column_name_from_given_column_number.java a GFG problem in Java
  Column_name_from_given_column_number.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#24 Create Automorphic_Number.java
  Automorphic_Number.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#23 Bellman Ford AlgoImplement.java
  BellmanFordAlgoImplement.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#26 maze path program added
  Print Maze Paths.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#29 Create Heap_sort.java
  Heap_sort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#28 Added quick sort code
  QuickSort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#34 Java solution added of problem with longest common subsequence with s…
  longest_common_subsequence_with_sum_k.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#33 Create Merge_sort.java
  Merge_sort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#32 Create Knapsack.java
  Knapsack.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#31 Create MedianOfSortedArrays.java
  JAVA SOLUTION/MedianOfSortedArrays.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#30 Create DoubleLoopStarPrinting.java
  DoubleLoopStarPrinting.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#35 Added pattern132.java
  pattern132.class
  pattern132.java
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#40 Added bubble sort .java
  bubblesort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#38 Created Graph algorithms folder
  Graph algorithms/BellmanFordAlgorithm.java
  Graph algorithms/DijkstrasAlgorithmMST.java
  Graph algorithms/DijkstrasAlgorithmSP.java
  Graph algorithms/FloodFill.java
  Graph algorithms/FloodFill_Mruganka.java
  Graph algorithms/FloydWarshallAlgorithm.java
  Graph algorithms/KruskalsAlgorithm.java
  Graph algorithms/LeesAlgorithm.java
  Graph algorithms/LeesAlgorithm_Mruganka.cpp.java
  Graph algorithms/MSTbyKruskal.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#46 Create Matrix_add.java
  Matrix_add.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#36 Added Floyd-Warshall Algorithm
  FloydWarshall.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#37 Create ConcatinateWords.java
  JAVA SOLUTION/ConcatinateWords.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#41 Added Selection Sort
  selectionSort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#42 Error handling
  Cycle Sort
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#43 Created simple ArrayList.java program
  ArrayList.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#44 Created Vstarpattern.java
  Vstarpattern.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#45 Create ComplexNo_add.java
  ComplexNo_add.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#48 Create armstrong number in java
  armstrong.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#51 added the program to show the implementation of interfaces in java.
  Interface.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#50 Create FindOccouranceIndicesInArray.java
  JAVA SOLUTION/FindOccouranceIndicesInArray.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#49 Create Currency Converter using java
  Currency_Converter.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#58 heapsort
  heapsort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#61 Create a palimdrome
  apalimdrome.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#60 Added BRS to Currency_Converter
  Currency_Converter.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#52 Create LongesPalindromicSubstring.java
  JAVA SOLUTION/LongesPalindromicSubstring.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#57 Added AndQueries Problem
  AndQueries.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#53 Create Pascal's_Triangle.java
  Pascal's_Triangle.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#59 CalculateNthFibonacciNumber
  CalculateNthFibonacciNumber
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#55 Updated RadixSort code which will work for negative and positive numbers
  Armstrong.java
  Java-problem-2023.iml
  RadixSort.java
  armstrong.java
  complexNo.java
  graph/algorithms/FloydWarshallAlgorithm.java
  java/solution/ConcatinateWords.java
  java/solution/FindOccouranceIndicesInArray.java
  matrixAdd.java
  q6.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#62 overloading
  overloading.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#63 Added Error Handling on BinarySearch
  BinarySearchExample.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#64 Create intersectionOfTwoArrays.java
  java/solution/intersectionOfTwoArrays.java
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#66 Create SelectionSort
  SelectionSort
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#65 Create InsertionSort
  InsertionSort
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#71 Create Fibonacci.java
  java/solution/Fibonacci.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#70 Added an error in case of negative numbers on Fibonnaci Sequence
  CalculateNthFibonacciNumber
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#69 Create BinarySearchTree.java
  BinarySearchTree.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#68 Create TimSortJava
  TimSortJava
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#67 Create Strings.java
  Strings.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#76 Create Tower_of_Hanoi.java
  Tower_of_Hanoi.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#75 Create SudokuSolver.java
  java/solution/SudokuSolver.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#74 Create Bubble_sort.java
  Bubble_sort.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#73 Create LinkedListReversal.java
  LinkedListReversal.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#72 Dijksta Algorithm in Java Added
  DijkstraAlgorithm.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#81 Added the code to simulated annealing using java
  SimulatedAnnealing.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#80 Create Email Masker Optimal solution in java
  EmailMaskerOptimised.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#79 Create Radix Sort Optimized solution in java
  RadixSortOptimized.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#77 Created LeeAlgorithm Optimized solution in java
  LeeAlgorithmOptimized.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#87 Create DijkstraShortestPath.java for more generic and work with any n…
  DijkstraShortestPath.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#86 Create TopologicalSortOptimized.java with more clearer understandable…
  TopologicalSortOptimized.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#85 Created PrintMazePaths Optimized solution in java
  PrintMazePathsOptimized.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#84 WordBreakProblem-Submits the solution of java problem #1
  WordBreak.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#83 rabin carp algorithm in java added
  all_subsequences_with_sum_equal_k.java
  longest_common_subsequence_with_sum_k.java
  rabin_carp_algorithm.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#82 Implementation of a Stack class in own way
  Stack.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#97 Submits the solution of java problem
  FibonacciSeries.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#96 Create FloodFillAlgorithm.java
  FloodFillAlgorithm.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#94 Code to Reverse a Stack
  Reverse_Stack.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#93 Create LinearSearchRecursion.java
  LinearSearchRecursion.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#91 Update ArrayList.java
  ArrayList.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#90 Create binarysearch_rec.java
  binarysearch_rec.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#89 Create stack_linked.java
  stack_linked.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#88 Improves the effeciency of selection sort
  impr_selec.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#100 Create Q_5.java
  Q_5.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#98 Create PermutationSequence.java
  PermutationSequence.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#101 Create Check_Even_Fibonacci.java
  Check_Even_Fibonacci.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#102 Revert 3 kriti142003 patch 3
  Rotate_array.java
  ThreeSum.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#103 Create KadaneAlgorithm.java
  java/solution/KadaneAlgorithm.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#106 0/1 Knapsack Problem in Java using dynamic programming
  java/solution/Knapsack.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#105 added Dijkstra's Shortest Path Algorithm
  Dijkstra's Shortest Path Algorithm.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted

#107 Create ShellSort
  ShellSort
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accept, hacktoberfest-accepted
